### ISSUE TITLE
Demo中的List和Menu的问题

### ISSUE THREAD

**Issue by Nicholas-Shen** [vum-team/vum#13]
1. Demo中的List界面, 在Android下页面无法上下滚动, iOS的可以.
2. Menu界面在iOS下,点击右上角Edit, 容易出现击穿,导致Title对应的Menu出现.

Android设备: 小米3
iOS设备: iphone6s

**Comment by lihongxun945** [comment]
感谢反馈，不过现在处在开发阶段，有问题是正常的

**Comment by lihongxun945** [comment]
刚才正好在master分支修复了 List 无法滚动的问题

**Comment by Nicholas-Shen** [comment]
期待这个项目.
另外, 在Demo中, 在Title上向左滑动, 可以看到整个页面会向左滑动大约10px的距离, 是不是padding或者margin的问题. 你可以看下.

**Comment by lihongxun945** [comment]
这个我发现了，还没解决。貌似不是简单的 padding 或者 margin 问题

**Comment by Nicholas-Shen** [comment]
刚刚Debug了一下, 原因是.nav 中有padding-right: .5rem; padding-left: .5rem; 而.title又设置了width为100%, 所以需要把.title的margin设置为0 -.5rem.

**Comment by lihongxun945** [comment]
赞，等我解决了记住滚动位置的问题之后看一下

**Comment by Nicholas-Shen** [comment]
OK

**Comment by lihongxun945** [comment]
你可以再看看，这三个问题应该解决了：
- List 无法滚动
- 页面横向滚
- 无法记住滚动位置
