### ISSUE TITLE
light7的功能现在是不是比这个vum多啊

### ISSUE THREAD

**Issue by df257** [vum-team/vum#23]
我只想专心学一款好的，结果发现了f7,然后又发现了sui,.......最后到这了....

**Comment by df257** [comment]
我发现作者真是做了一大堆框架，刚才又发现一个了。。。jquery weui

**Comment by lihongxun945** [comment]
恭喜入坑。目前保持更新的是 `jquery weui` 和 `vum`，另外两个不再更新了
